# Generated by Django 2.2.4 on 2020-06-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190829_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_buiding',
            field=models.BooleanField(null=True, verbose_name='Новостройка'),
        ),
    ]
